version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: postgres-db
    volumes:
      - ./notifier-pgdata:/var/lib/postgresql/data
    ports:
      - "6002:5432"
  notifier:
    build:
      context: ../../
      dockerfile: ./devops/dev/Dockerfile
    image: notifier-backend:latest
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - APP_PORT=${APP_PORT}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - MIXPANEL_TOKEN=${MIXPANEL_TOKEN}
    ports:
      - "6003:3000"
      - "6001:9229"
    container_name: notifier-backend-container
    depends_on:
      - db
    volumes:
      - ../../:/app
      - ../../node_modules:/app/node_modules
      - /app/node_modules/bcrypt/
volumes:
  notifier-pgdata:
