name: GitHub Actions Demo
on:
  push:
      branches:
        - master
jobs:
  build-and-deploy-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build
        run: docker build -f ./devops/prod/Dockerfile -t kortez1337/notifier-backend:latest .

      - name: Docker push
        run: docker push kortez1337/notifier-backend:latest
